[package]
name = "dust_dds_telescope"
version = "0.1.0"
authors = [
    "Joao Rebelo <jrebelo@s2e-systems.com>",
    "Stefan Kimmer <skimmer@s2e-systems.com>",
]
license = "Apache-2.0"
edition = "2021"
description = "Dust DDS Telescope"

[dependencies]
dust_dds = { path = "../dds" }
