[package]
name = "micro_dust_dds_interface"
description = "Micro Dust DDS Demo Interface"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
dust_dds = { path = "../../dds", default-features = false }
