struct Point {
    double x;
    double y;
};

struct ChessSquare {
    @key char column;
    @key unsigned short line;
};

struct HelloWorld {
    string message;
    unsigned long id;
};

struct Sentence {
    sequence<wstring> words;
};