/*
 * Module IDL example
 */

/// Game module
module Game
{
    /// Chess
    module Chess
    {
        enum ChessPiece
        {
            Pawn, Rook, Knight, Bishop, Queen, King
        };

        struct ChessSquare
        {
            char column;          // A, B, ..., G
            unsigned short line;  // 1, 2, ..., 8
        };
    };

    module Cards
    {
        enum Suit { Spades, Hearts, Diamonds, Clubs /*, NoTrump */ };
    };
};

struct Point
{
    double x;
    double y;
};