const string MY_STRING = "BAR";
const short MY_SHORT = -1;
const unsigned short MY_USHORT = 2;
const long MY_LONG = -3;
const unsigned long MY_ULONG = 4;
const long long MY_LONGLONG = -5;
const unsigned long long MY_ULONGLONG = 6;
const float MY_FLOAT = 1.5;
const double MY_DOUBLE = 2.5;
const char MY_CHAR = 'a';
const boolean MY_BOOL = TRUE;
const octet MY_OCTET = 7;
const int8 MY_INT8 = -8;
const uint8 MY_UINT8 = 8;
const int16 MY_INT16 = -16;
const uint16 MY_UINT16 = 16;
const int32 MY_INT32 = -32;
const uint32 MY_UINT32 = 32;
const int64 MY_INT64 = -64;
const uint64 MY_UINT64 = 64;