struct Person {
    @id(1) string name;
    @id(2) int32 age;
    @id(3) double height;
};

struct Message {
    @key @id(1) int32 id;
    @id(2) string content;
    @id(3) int64 timestamp;
};
